// HARVESTFELL — settlement map
// overworldCell: 190,644  walls: 28x28  hasWalls: true
(function(){
  window.SETTLEMENTS = window.SETTLEMENTS || {};
  const m = {};
  function t(x,y,type,name,extra={}){ m[`${x},${y}`] = Object.assign({type,name},extra); }

  // ── MAP CELLS ──────────────────────────────────────────────────────────────
  t(-14,28,'wall','Wall');
  t(-13,28,'wall','Wall');
  t(-12,28,'wall','Wall');
  t(-11,28,'wall','Wall');
  t(-10,28,'wall','Wall');
  t(-9,28,'wall','Wall');
  t(-8,28,'wall','Wall');
  t(-7,28,'wall','Wall');
  t(-6,28,'wall','Wall');
  t(-5,28,'wall','Wall');
  t(-4,28,'wall','Wall');
  t(-3,28,'wall','Wall');
  t(-2,28,'wall','Wall');
  t(-1,28,'wall','Wall');
  t(0,28,'gate','North Gate',{"exit":{"layer":"overworld","pos":{"x":190,"y":634}}});
  t(1,28,'wall','Wall');
  t(2,28,'wall','Wall');
  t(3,28,'wall','Wall');
  t(4,28,'wall','Wall');
  t(5,28,'wall','Wall');
  t(6,28,'wall','Wall');
  t(7,28,'wall','Wall');
  t(8,28,'wall','Wall');
  t(9,28,'wall','Wall');
  t(10,28,'wall','Wall');
  t(11,28,'wall','Wall');
  t(12,28,'wall','Wall');
  t(13,28,'wall','Wall');
  t(14,28,'wall','Wall');
  t(-14,27,'wall','Wall');
  t(0,27,'street','Main Street');
  t(14,27,'wall','Wall');
  t(-14,26,'wall','Wall');
  t(-13,26,'building','Building');
  t(-12,26,'building','Building');
  t(-11,26,'building','Building');
  t(-10,26,'building','Building');
  t(-9,26,'building','Building');
  t(-8,26,'building','Building');
  t(-7,26,'building','Building');
  t(-6,26,'door','The Golden Sheaf',{"enter":{"layer":"interior","id":"harvestfell_inn","entryPos":{"x":1,"y":1}}});
  t(-5,26,'building','Building');
  t(-4,26,'building','Building');
  t(-3,26,'building','Building');
  t(-2,26,'building','Building');
  t(0,26,'street','Main Street');
  t(2,26,'building','Building');
  t(3,26,'building','Building');
  t(4,26,'building','Building');
  t(5,26,'building','Building');
  t(6,26,'door','Harvest Market',{"enter":{"layer":"interior","id":"harvestfell_market","entryPos":{"x":1,"y":1}}});
  t(7,26,'building','Building');
  t(8,26,'building','Building');
  t(9,26,'building','Building');
  t(10,26,'building','Building');
  t(11,26,'building','Building');
  t(12,26,'building','Building');
  t(13,26,'building','Building');
  t(14,26,'wall','Wall');
  t(-14,25,'wall','Wall');
  t(-13,25,'building','Building');
  t(-12,25,'building','Building');
  t(-11,25,'building','Building');
  t(-10,25,'building','Building');
  t(-9,25,'building','Building');
  t(-8,25,'building','Building');
  t(-7,25,'building','Building');
  t(-6,25,'building','Building');
  t(-5,25,'building','Building');
  t(-4,25,'building','Building');
  t(-3,25,'building','Building');
  t(-2,25,'building','Building');
  t(0,25,'street','Main Street');
  t(2,25,'building','Building');
  t(3,25,'building','Building');
  t(4,25,'building','Building');
  t(5,25,'building','Building');
  t(6,25,'building','Building');
  t(7,25,'building','Building');
  t(8,25,'building','Building');
  t(9,25,'building','Building');
  t(10,25,'building','Building');
  t(11,25,'building','Building');
  t(12,25,'building','Building');
  t(13,25,'building','Building');
  t(14,25,'wall','Wall');
  t(-14,24,'wall','Wall');
  t(-13,24,'building','Building');
  t(-12,24,'building','Building');
  t(-11,24,'building','Building');
  t(-10,24,'building','Building');
  t(-9,24,'building','Building');
  t(-8,24,'building','Building');
  t(-7,24,'building','Building');
  t(-6,24,'building','Building');
  t(-5,24,'building','Building');
  t(-4,24,'building','Building');
  t(-3,24,'building','Building');
  t(-2,24,'building','Building');
  t(0,24,'street','Main Street');
  t(2,24,'building','Building');
  t(3,24,'building','Building');
  t(4,24,'building','Building');
  t(5,24,'building','Building');
  t(6,24,'building','Building');
  t(7,24,'building','Building');
  t(8,24,'building','Building');
  t(9,24,'building','Building');
  t(10,24,'building','Building');
  t(11,24,'building','Building');
  t(12,24,'building','Building');
  t(13,24,'building','Building');
  t(14,24,'wall','Wall');
  t(-14,23,'wall','Wall');
  t(-13,23,'building','Building');
  t(-12,23,'building','Building');
  t(-11,23,'building','Building');
  t(-10,23,'building','Building');
  t(-9,23,'building','Building');
  t(-8,23,'building','Building');
  t(-7,23,'building','Building');
  t(-6,23,'building','Building');
  t(-5,23,'building','Building');
  t(-4,23,'building','Building');
  t(-3,23,'building','Building');
  t(-2,23,'building','Building');
  t(0,23,'street','Main Street');
  t(2,23,'building','Building');
  t(3,23,'building','Building');
  t(4,23,'building','Building');
  t(5,23,'building','Building');
  t(6,23,'building','Building');
  t(7,23,'building','Building');
  t(8,23,'building','Building');
  t(9,23,'building','Building');
  t(10,23,'building','Building');
  t(11,23,'building','Building');
  t(12,23,'building','Building');
  t(13,23,'building','Building');
  t(14,23,'wall','Wall');
  t(-14,22,'wall','Wall');
  t(-13,22,'building','Building');
  t(-12,22,'building','Building');
  t(-11,22,'building','Building');
  t(-10,22,'building','Building');
  t(-9,22,'building','Building');
  t(-8,22,'building','Building');
  t(-7,22,'building','Building');
  t(-6,22,'building','Building');
  t(-5,22,'building','Building');
  t(-4,22,'building','Building');
  t(-3,22,'building','Building');
  t(-2,22,'building','Building');
  t(0,22,'street','Main Street');
  t(2,22,'building','Building');
  t(3,22,'building','Building');
  t(4,22,'building','Building');
  t(5,22,'building','Building');
  t(6,22,'building','Building');
  t(7,22,'building','Building');
  t(8,22,'building','Building');
  t(9,22,'building','Building');
  t(10,22,'building','Building');
  t(11,22,'building','Building');
  t(12,22,'building','Building');
  t(13,22,'building','Building');
  t(14,22,'wall','Wall');
  t(-14,21,'wall','Wall');
  t(-13,21,'building','Building');
  t(-12,21,'building','Building');
  t(-11,21,'building','Building');
  t(-10,21,'building','Building');
  t(-9,21,'building','Building');
  t(-8,21,'building','Building');
  t(-7,21,'building','Building');
  t(-6,21,'building','Building');
  t(-5,21,'building','Building');
  t(-4,21,'building','Building');
  t(-3,21,'building','Building');
  t(-2,21,'building','Building');
  t(0,21,'street','Main Street');
  t(2,21,'building','Building');
  t(3,21,'building','Building');
  t(4,21,'building','Building');
  t(5,21,'building','Building');
  t(6,21,'building','Building');
  t(7,21,'building','Building');
  t(8,21,'building','Building');
  t(9,21,'building','Building');
  t(10,21,'building','Building');
  t(11,21,'building','Building');
  t(12,21,'building','Building');
  t(13,21,'building','Building');
  t(14,21,'wall','Wall');
  t(-14,20,'wall','Wall');
  t(-13,20,'building','Building');
  t(-12,20,'building','Building');
  t(-11,20,'building','Building');
  t(-10,20,'building','Building');
  t(-9,20,'building','Building');
  t(-8,20,'building','Building');
  t(-7,20,'building','Building');
  t(-6,20,'building','Building');
  t(-5,20,'building','Building');
  t(-4,20,'building','Building');
  t(-3,20,'building','Building');
  t(-2,20,'building','Building');
  t(0,20,'street','Main Street');
  t(2,20,'building','Building');
  t(3,20,'building','Building');
  t(4,20,'building','Building');
  t(5,20,'building','Building');
  t(6,20,'building','Building');
  t(7,20,'building','Building');
  t(8,20,'building','Building');
  t(9,20,'building','Building');
  t(10,20,'building','Building');
  t(11,20,'building','Building');
  t(12,20,'building','Building');
  t(13,20,'building','Building');
  t(14,20,'wall','Wall');
  t(-14,19,'wall','Wall');
  t(-13,19,'building','Building');
  t(-12,19,'building','Building');
  t(-11,19,'building','Building');
  t(-10,19,'building','Building');
  t(-9,19,'building','Building');
  t(-8,19,'building','Building');
  t(-7,19,'building','Building');
  t(-6,19,'building','Building');
  t(-5,19,'building','Building');
  t(-4,19,'building','Building');
  t(-3,19,'building','Building');
  t(-2,19,'building','Building');
  t(0,19,'street','Main Street');
  t(2,19,'building','Building');
  t(3,19,'building','Building');
  t(4,19,'building','Building');
  t(5,19,'building','Building');
  t(6,19,'building','Building');
  t(7,19,'building','Building');
  t(8,19,'building','Building');
  t(9,19,'building','Building');
  t(10,19,'building','Building');
  t(11,19,'building','Building');
  t(12,19,'building','Building');
  t(13,19,'building','Building');
  t(14,19,'wall','Wall');
  t(-14,18,'wall','Wall');
  t(-13,18,'building','Building');
  t(-12,18,'building','Building');
  t(-11,18,'building','Building');
  t(-10,18,'building','Building');
  t(-9,18,'building','Building');
  t(-8,18,'building','Building');
  t(-7,18,'building','Building');
  t(-6,18,'building','Building');
  t(-5,18,'building','Building');
  t(-4,18,'building','Building');
  t(-3,18,'building','Building');
  t(-2,18,'building','Building');
  t(0,18,'street','Main Street');
  t(2,18,'building','Building');
  t(3,18,'building','Building');
  t(4,18,'building','Building');
  t(5,18,'building','Building');
  t(6,18,'building','Building');
  t(7,18,'building','Building');
  t(8,18,'building','Building');
  t(9,18,'building','Building');
  t(10,18,'building','Building');
  t(11,18,'building','Building');
  t(12,18,'building','Building');
  t(13,18,'building','Building');
  t(14,18,'wall','Wall');
  t(-14,17,'wall','Wall');
  t(-13,17,'building','Building');
  t(-12,17,'building','Building');
  t(-11,17,'building','Building');
  t(-10,17,'building','Building');
  t(-9,17,'building','Building');
  t(-8,17,'building','Building');
  t(-7,17,'building','Building');
  t(-6,17,'building','Building');
  t(-5,17,'building','Building');
  t(-4,17,'building','Building');
  t(-3,17,'building','Building');
  t(-2,17,'building','Building');
  t(0,17,'street','Main Street');
  t(2,17,'building','Building');
  t(3,17,'building','Building');
  t(4,17,'building','Building');
  t(5,17,'building','Building');
  t(6,17,'building','Building');
  t(7,17,'building','Building');
  t(8,17,'building','Building');
  t(9,17,'building','Building');
  t(10,17,'building','Building');
  t(11,17,'building','Building');
  t(12,17,'building','Building');
  t(13,17,'building','Building');
  t(14,17,'wall','Wall');
  t(-14,16,'wall','Wall');
  t(-13,16,'building','Building');
  t(-12,16,'building','Building');
  t(-11,16,'building','Building');
  t(-10,16,'building','Building');
  t(-9,16,'building','Building');
  t(-8,16,'building','Building');
  t(-7,16,'building','Building');
  t(-6,16,'building','Building');
  t(-5,16,'building','Building');
  t(-4,16,'building','Building');
  t(-3,16,'building','Building');
  t(-2,16,'building','Building');
  t(0,16,'street','Main Street');
  t(2,16,'building','Building');
  t(3,16,'building','Building');
  t(4,16,'building','Building');
  t(5,16,'building','Building');
  t(6,16,'building','Building');
  t(7,16,'building','Building');
  t(8,16,'building','Building');
  t(9,16,'building','Building');
  t(10,16,'building','Building');
  t(11,16,'building','Building');
  t(12,16,'building','Building');
  t(13,16,'building','Building');
  t(14,16,'wall','Wall');
  t(-14,15,'wall','Wall');
  t(0,15,'street','Main Street');
  t(14,15,'wall','Wall');
  t(-14,14,'wall','Wall');
  t(-13,14,'street','Cross Street');
  t(-12,14,'street','Cross Street');
  t(-11,14,'street','Cross Street');
  t(-10,14,'street','Cross Street');
  t(-9,14,'street','Cross Street');
  t(-8,14,'street','Cross Street');
  t(-7,14,'street','Cross Street');
  t(-6,14,'street','Cross Street');
  t(-5,14,'street','Cross Street');
  t(-4,14,'street','Cross Street');
  t(-3,14,'street','Cross Street');
  t(-2,14,'street','Cross Street');
  t(-1,14,'street','Cross Street');
  t(0,14,'street','Cross Street');
  t(1,14,'street','Cross Street');
  t(2,14,'street','Cross Street');
  t(3,14,'street','Cross Street');
  t(4,14,'street','Cross Street');
  t(5,14,'street','Cross Street');
  t(6,14,'street','Cross Street');
  t(7,14,'street','Cross Street');
  t(8,14,'street','Cross Street');
  t(9,14,'street','Cross Street');
  t(10,14,'street','Cross Street');
  t(11,14,'street','Cross Street');
  t(12,14,'street','Cross Street');
  t(13,14,'street','Cross Street');
  t(14,14,'wall','Wall');
  t(-14,13,'wall','Wall');
  t(-13,13,'building','Building');
  t(-12,13,'building','Building');
  t(-11,13,'building','Building');
  t(-10,13,'building','Building');
  t(-9,13,'building','Building');
  t(-8,13,'building','Building');
  t(-7,13,'building','Building');
  t(-6,13,'building','Building');
  t(-5,13,'building','Building');
  t(-4,13,'building','Building');
  t(-3,13,'building','Building');
  t(-2,13,'building','Building');
  t(0,13,'street','Main Street');
  t(2,13,'building','Building');
  t(3,13,'building','Building');
  t(4,13,'building','Building');
  t(5,13,'building','Building');
  t(6,13,'building','Building');
  t(7,13,'building','Building');
  t(8,13,'building','Building');
  t(9,13,'building','Building');
  t(10,13,'building','Building');
  t(11,13,'building','Building');
  t(12,13,'building','Building');
  t(13,13,'building','Building');
  t(14,13,'wall','Wall');
  t(-14,12,'wall','Wall');
  t(-13,12,'building','Building');
  t(-12,12,'building','Building');
  t(-11,12,'building','Building');
  t(-10,12,'building','Building');
  t(-9,12,'building','Building');
  t(-8,12,'building','Building');
  t(-7,12,'building','Building');
  t(-6,12,'door','Temple of the Sea',{"enter":{"layer":"interior","id":"harvestfell_temple","entryPos":{"x":1,"y":1}}});
  t(-5,12,'building','Building');
  t(-4,12,'building','Building');
  t(-3,12,'building','Building');
  t(-2,12,'building','Building');
  t(0,12,'street','Main Street');
  t(2,12,'building','Building');
  t(3,12,'building','Building');
  t(4,12,'building','Building');
  t(5,12,'building','Building');
  t(6,12,'building','Building');
  t(7,12,'building','Building');
  t(8,12,'building','Building');
  t(9,12,'building','Building');
  t(10,12,'building','Building');
  t(11,12,'building','Building');
  t(12,12,'building','Building');
  t(13,12,'building','Building');
  t(14,12,'wall','Wall');
  t(-14,11,'wall','Wall');
  t(-13,11,'building','Building');
  t(-12,11,'building','Building');
  t(-11,11,'building','Building');
  t(-10,11,'building','Building');
  t(-9,11,'building','Building');
  t(-8,11,'building','Building');
  t(-7,11,'building','Building');
  t(-6,11,'building','Building');
  t(-5,11,'building','Building');
  t(-4,11,'building','Building');
  t(-3,11,'building','Building');
  t(-2,11,'building','Building');
  t(0,11,'street','Main Street');
  t(2,11,'building','Building');
  t(3,11,'building','Building');
  t(4,11,'building','Building');
  t(5,11,'building','Building');
  t(6,11,'building','Building');
  t(7,11,'building','Building');
  t(8,11,'building','Building');
  t(9,11,'building','Building');
  t(10,11,'building','Building');
  t(11,11,'building','Building');
  t(12,11,'building','Building');
  t(13,11,'building','Building');
  t(14,11,'wall','Wall');
  t(-14,10,'wall','Wall');
  t(-13,10,'building','Building');
  t(-12,10,'building','Building');
  t(-11,10,'building','Building');
  t(-10,10,'building','Building');
  t(-9,10,'building','Building');
  t(-8,10,'building','Building');
  t(-7,10,'building','Building');
  t(-6,10,'building','Building');
  t(-5,10,'building','Building');
  t(-4,10,'building','Building');
  t(-3,10,'building','Building');
  t(-2,10,'building','Building');
  t(0,10,'street','Main Street');
  t(2,10,'building','Building');
  t(3,10,'building','Building');
  t(4,10,'building','Building');
  t(5,10,'building','Building');
  t(6,10,'building','Building');
  t(7,10,'building','Building');
  t(8,10,'building','Building');
  t(9,10,'building','Building');
  t(10,10,'building','Building');
  t(11,10,'building','Building');
  t(12,10,'building','Building');
  t(13,10,'building','Building');
  t(14,10,'wall','Wall');
  t(-14,9,'wall','Wall');
  t(-13,9,'building','Building');
  t(-12,9,'building','Building');
  t(-11,9,'building','Building');
  t(-10,9,'building','Building');
  t(-9,9,'building','Building');
  t(-8,9,'building','Building');
  t(-7,9,'building','Building');
  t(-6,9,'building','Building');
  t(-5,9,'building','Building');
  t(-4,9,'building','Building');
  t(-3,9,'building','Building');
  t(-2,9,'building','Building');
  t(0,9,'street','Main Street');
  t(2,9,'building','Building');
  t(3,9,'building','Building');
  t(4,9,'building','Building');
  t(5,9,'building','Building');
  t(6,9,'building','Building');
  t(7,9,'building','Building');
  t(8,9,'building','Building');
  t(9,9,'building','Building');
  t(10,9,'building','Building');
  t(11,9,'building','Building');
  t(12,9,'building','Building');
  t(13,9,'building','Building');
  t(14,9,'wall','Wall');
  t(-14,8,'wall','Wall');
  t(-13,8,'building','Building');
  t(-12,8,'building','Building');
  t(-11,8,'building','Building');
  t(-10,8,'building','Building');
  t(-9,8,'building','Building');
  t(-8,8,'building','Building');
  t(-7,8,'building','Building');
  t(-6,8,'building','Building');
  t(-5,8,'building','Building');
  t(-4,8,'building','Building');
  t(-3,8,'building','Building');
  t(-2,8,'building','Building');
  t(0,8,'street','Main Street');
  t(2,8,'building','Building');
  t(3,8,'building','Building');
  t(4,8,'building','Building');
  t(5,8,'building','Building');
  t(6,8,'building','Building');
  t(7,8,'building','Building');
  t(8,8,'building','Building');
  t(9,8,'building','Building');
  t(10,8,'building','Building');
  t(11,8,'building','Building');
  t(12,8,'building','Building');
  t(13,8,'building','Building');
  t(14,8,'wall','Wall');
  t(-14,7,'wall','Wall');
  t(-13,7,'building','Building');
  t(-12,7,'building','Building');
  t(-11,7,'building','Building');
  t(-10,7,'building','Building');
  t(-9,7,'building','Building');
  t(-8,7,'building','Building');
  t(-7,7,'building','Building');
  t(-6,7,'building','Building');
  t(-5,7,'building','Building');
  t(-4,7,'building','Building');
  t(-3,7,'building','Building');
  t(-2,7,'building','Building');
  t(0,7,'street','Main Street');
  t(2,7,'building','Building');
  t(3,7,'building','Building');
  t(4,7,'building','Building');
  t(5,7,'building','Building');
  t(6,7,'building','Building');
  t(7,7,'building','Building');
  t(8,7,'building','Building');
  t(9,7,'building','Building');
  t(10,7,'building','Building');
  t(11,7,'building','Building');
  t(12,7,'building','Building');
  t(13,7,'building','Building');
  t(14,7,'wall','Wall');
  t(-14,6,'wall','Wall');
  t(-13,6,'building','Building');
  t(-12,6,'building','Building');
  t(-11,6,'building','Building');
  t(-10,6,'building','Building');
  t(-9,6,'building','Building');
  t(-8,6,'building','Building');
  t(-7,6,'building','Building');
  t(-6,6,'building','Building');
  t(-5,6,'building','Building');
  t(-4,6,'building','Building');
  t(-3,6,'building','Building');
  t(-2,6,'building','Building');
  t(0,6,'street','Main Street');
  t(2,6,'building','Building');
  t(3,6,'building','Building');
  t(4,6,'building','Building');
  t(5,6,'building','Building');
  t(6,6,'building','Building');
  t(7,6,'building','Building');
  t(8,6,'building','Building');
  t(9,6,'building','Building');
  t(10,6,'building','Building');
  t(11,6,'building','Building');
  t(12,6,'building','Building');
  t(13,6,'building','Building');
  t(14,6,'wall','Wall');
  t(-14,5,'wall','Wall');
  t(-13,5,'building','Building');
  t(-12,5,'building','Building');
  t(-11,5,'building','Building');
  t(-10,5,'building','Building');
  t(-9,5,'building','Building');
  t(-8,5,'building','Building');
  t(-7,5,'building','Building');
  t(-6,5,'building','Building');
  t(-5,5,'building','Building');
  t(-4,5,'building','Building');
  t(-3,5,'building','Building');
  t(-2,5,'building','Building');
  t(0,5,'street','Main Street');
  t(2,5,'building','Building');
  t(3,5,'building','Building');
  t(4,5,'building','Building');
  t(5,5,'building','Building');
  t(6,5,'building','Building');
  t(7,5,'building','Building');
  t(8,5,'building','Building');
  t(9,5,'building','Building');
  t(10,5,'building','Building');
  t(11,5,'building','Building');
  t(12,5,'building','Building');
  t(13,5,'building','Building');
  t(14,5,'wall','Wall');
  t(-14,4,'wall','Wall');
  t(-13,4,'building','Building');
  t(-12,4,'building','Building');
  t(-11,4,'building','Building');
  t(-10,4,'building','Building');
  t(-9,4,'building','Building');
  t(-8,4,'building','Building');
  t(-7,4,'building','Building');
  t(-6,4,'building','Building');
  t(-5,4,'building','Building');
  t(-4,4,'building','Building');
  t(-3,4,'building','Building');
  t(-2,4,'building','Building');
  t(0,4,'street','Main Street');
  t(2,4,'building','Building');
  t(3,4,'building','Building');
  t(4,4,'building','Building');
  t(5,4,'building','Building');
  t(6,4,'building','Building');
  t(7,4,'building','Building');
  t(8,4,'building','Building');
  t(9,4,'building','Building');
  t(10,4,'building','Building');
  t(11,4,'building','Building');
  t(12,4,'building','Building');
  t(13,4,'building','Building');
  t(14,4,'wall','Wall');
  t(-14,3,'wall','Wall');
  t(-13,3,'building','Building');
  t(-12,3,'building','Building');
  t(-11,3,'building','Building');
  t(-10,3,'building','Building');
  t(-9,3,'building','Building');
  t(-8,3,'building','Building');
  t(-7,3,'building','Building');
  t(-6,3,'building','Building');
  t(-5,3,'building','Building');
  t(-4,3,'building','Building');
  t(-3,3,'building','Building');
  t(-2,3,'building','Building');
  t(0,3,'street','Main Street');
  t(2,3,'building','Building');
  t(3,3,'building','Building');
  t(4,3,'building','Building');
  t(5,3,'building','Building');
  t(6,3,'building','Building');
  t(7,3,'building','Building');
  t(8,3,'building','Building');
  t(9,3,'building','Building');
  t(10,3,'building','Building');
  t(11,3,'building','Building');
  t(12,3,'building','Building');
  t(13,3,'building','Building');
  t(14,3,'wall','Wall');
  t(-14,2,'wall','Wall');
  t(-13,2,'building','Building');
  t(-12,2,'building','Building');
  t(-11,2,'building','Building');
  t(-10,2,'building','Building');
  t(-9,2,'building','Building');
  t(-8,2,'building','Building');
  t(-7,2,'building','Building');
  t(-6,2,'building','Building');
  t(-5,2,'building','Building');
  t(-4,2,'building','Building');
  t(-3,2,'building','Building');
  t(-2,2,'building','Building');
  t(0,2,'street','Main Street');
  t(2,2,'building','Building');
  t(3,2,'building','Building');
  t(4,2,'building','Building');
  t(5,2,'building','Building');
  t(6,2,'building','Building');
  t(7,2,'building','Building');
  t(8,2,'building','Building');
  t(9,2,'building','Building');
  t(10,2,'building','Building');
  t(11,2,'building','Building');
  t(12,2,'building','Building');
  t(13,2,'building','Building');
  t(14,2,'wall','Wall');
  t(-14,1,'wall','Wall');
  t(0,1,'street','Main Street');
  t(14,1,'wall','Wall');
  t(-14,0,'wall','Wall');
  t(-13,0,'wall','Wall');
  t(-12,0,'wall','Wall');
  t(-11,0,'wall','Wall');
  t(-10,0,'wall','Wall');
  t(-9,0,'wall','Wall');
  t(-8,0,'wall','Wall');
  t(-7,0,'wall','Wall');
  t(-6,0,'wall','Wall');
  t(-5,0,'wall','Wall');
  t(-4,0,'wall','Wall');
  t(-3,0,'wall','Wall');
  t(-2,0,'wall','Wall');
  t(-1,0,'wall','Wall');
  t(0,0,'gate','South Gate',{"exit":{"layer":"overworld","pos":{"x":190,"y":654}}});
  t(1,0,'wall','Wall');
  t(2,0,'wall','Wall');
  t(3,0,'wall','Wall');
  t(4,0,'wall','Wall');
  t(5,0,'wall','Wall');
  t(6,0,'wall','Wall');
  t(7,0,'wall','Wall');
  t(8,0,'wall','Wall');
  t(9,0,'wall','Wall');
  t(10,0,'wall','Wall');
  t(11,0,'wall','Wall');
  t(12,0,'wall','Wall');
  t(13,0,'wall','Wall');
  t(14,0,'wall','Wall');

  window.SETTLEMENTS['harvestfell'] = {
    map: m,
    name: "Harvestfell",
    hasWalls: true,
    entryPos: {x:0, y:2},
    overworldCell: {x:190, y:644},
    description: "",
  };
})();
