// BLANK — interior map
(function(){
  window.SETTLEMENTS = window.SETTLEMENTS || {};
  const m = {};
  function t(x,y,type,name,extra={}){ m[`${x},${y}`] = Object.assign({type,name},extra); }

  // MAP CELLS
  t(0,0,'wall','Wall');
  t(1,0,'wall','Wall');
  t(2,0,'wall','Wall');
  t(3,0,'wall','Wall');
  t(4,0,'wall','Wall');
  t(5,0,'wall','Wall');
  t(6,0,'door','Entrance');
  t(7,0,'wall','Wall');
  t(8,0,'wall','Wall');
  t(9,0,'wall','Wall');
  t(10,0,'wall','Wall');
  t(11,0,'wall','Wall');
  t(12,0,'wall','Wall');
  t(13,0,'wall','Wall');
  t(0,1,'wall','Wall');
  t(1,1,'floor_v','Floor', {terrainStyle:3});
  t(2,1,'floor_v','Floor', {terrainStyle:3});
  t(3,1,'floor_v','Floor', {terrainStyle:3});
  t(4,1,'floor_v','Floor', {terrainStyle:3});
  t(5,1,'floor_v','Floor', {terrainStyle:3});
  t(6,1,'floor_v','Floor', {terrainStyle:3});
  t(7,1,'floor_v','Floor', {terrainStyle:3});
  t(8,1,'floor_v','Floor', {terrainStyle:3});
  t(9,1,'door','Floor', {objVariant:0,objStyle:3,objLinen:3});
  t(10,1,'floor_v','Floor', {terrainStyle:3,objVariant:0,objStyle:3,objLinen:3});
  t(11,1,'floor_v','Floor', {terrainStyle:3});
  t(12,1,'floor_v','Floor', {terrainStyle:3});
  t(13,1,'wall','Wall');
  t(0,2,'wall','Wall');
  t(1,2,'floor_v','Floor', {terrainStyle:3,object:"table_r",objVariant:0,objLinen:3});
  t(2,2,'floor_v','Floor', {terrainStyle:3});
  t(3,2,'floor_v','Floor', {terrainStyle:3});
  t(4,2,'floor_v','Floor', {terrainStyle:3});
  t(5,2,'floor_v','Floor', {terrainStyle:3});
  t(6,2,'floor_v','Floor', {terrainStyle:3,object:"stool",objVariant:0,objLinen:3});
  t(7,2,'floor_v','Floor', {terrainStyle:3});
  t(8,2,'floor_v','Floor', {terrainStyle:3});
  t(9,2,'wall','Floor', {objVariant:0,objStyle:3,objLinen:3});
  t(10,2,'floor_v','Floor', {terrainStyle:3});
  t(11,2,'floor_v','Floor', {terrainStyle:3});
  t(12,2,'floor_v','Floor', {terrainStyle:3});
  t(13,2,'wall','Wall');
  t(0,3,'wall','Wall');
  t(1,3,'floor_v','Floor', {terrainStyle:3,object:"cauldron",objVariant:0,objLinen:3});
  t(2,3,'floor_v','Floor', {terrainStyle:3});
  t(3,3,'floor_v','Floor', {terrainStyle:3});
  t(4,3,'floor_v','Floor', {terrainStyle:3});
  t(5,3,'floor_v','Floor', {terrainStyle:3});
  t(6,3,'floor_v','Floor', {terrainStyle:3,object:"table_l",objVariant:0,objLinen:3});
  t(7,3,'floor_v','Floor', {terrainStyle:3});
  t(8,3,'floor_v','Floor', {terrainStyle:3});
  t(9,3,'wall','Floor', {objVariant:0,objStyle:3,objLinen:3});
  t(10,3,'floor_v','Floor', {terrainStyle:3});
  t(11,3,'floor_v','Floor', {terrainStyle:3});
  t(12,3,'floor_v','Floor', {terrainStyle:3});
  t(13,3,'wall','Wall');
  t(0,4,'wall','Wall');
  t(1,4,'floor_v','Floor', {terrainStyle:3,object:"fireplace",rotation:90,objVariant:0,objLinen:3});
  t(2,4,'floor_v','Floor', {terrainStyle:3});
  t(3,4,'floor_v','Floor', {terrainStyle:3});
  t(4,4,'floor_v','Floor', {terrainStyle:3});
  t(5,4,'floor_v','Floor', {terrainStyle:3});
  t(6,4,'floor_v','Floor', {terrainStyle:3,object:"stool",objVariant:0,objLinen:3});
  t(7,4,'floor_v','Floor', {terrainStyle:3,object:"stool",objVariant:0,objLinen:3});
  t(8,4,'floor_v','Floor', {terrainStyle:3});
  t(9,4,'wall','Floor', {objVariant:0,objStyle:3,objLinen:3});
  t(10,4,'floor_v','Floor', {terrainStyle:3});
  t(11,4,'floor_v','Floor', {terrainStyle:3});
  t(12,4,'floor_v','Floor', {terrainStyle:3});
  t(13,4,'wall','Wall');
  t(0,5,'wall','Wall');
  t(1,5,'floor_v','Floor', {terrainStyle:3,object:"basin",rotation:90,objVariant:0,objLinen:3});
  t(2,5,'floor_v','Floor', {terrainStyle:3});
  t(3,5,'floor_v','Floor', {terrainStyle:3});
  t(4,5,'floor_v','Floor', {terrainStyle:3});
  t(5,5,'floor_v','Floor', {terrainStyle:3});
  t(6,5,'floor_v','Floor', {terrainStyle:3});
  t(7,5,'floor_v','Floor', {terrainStyle:3});
  t(8,5,'floor_v','Floor', {terrainStyle:3});
  t(9,5,'wall','Floor', {objVariant:0,objStyle:3,objLinen:3});
  t(10,5,'floor_v','Floor', {terrainStyle:3});
  t(11,5,'floor_v','Floor', {terrainStyle:3,object:"bed_d",objVariant:0,objLinen:3});
  t(12,5,'floor_v','Floor', {terrainStyle:3,object:"drawers",rotation:180,objVariant:0,objStyle:3,objLinen:3});
  t(13,5,'wall','Wall');
  t(0,6,'wall','Wall');
  t(1,6,'wall','Floor');
  t(2,6,'wall','Floor');
  t(3,6,'wall','Floor');
  t(4,6,'wall','Floor');
  t(5,6,'wall','Floor');
  t(6,6,'wall','Floor');
  t(7,6,'wall','Floor');
  t(8,6,'wall','Floor');
  t(9,6,'wall','Floor');
  t(10,6,'wall','Floor');
  t(11,6,'wall','Floor');
  t(12,6,'wall','Floor');
  t(13,6,'wall','Wall');
  t(0,7,'interior','Wall');
  t(1,7,'interior','Floor');
  t(2,7,'interior','Floor');
  t(3,7,'interior','Floor');
  t(4,7,'interior','Floor');
  t(5,7,'interior','Floor');
  t(6,7,'interior','Floor');
  t(7,7,'interior','Floor');
  t(8,7,'interior','Floor');
  t(9,7,'interior','Floor');
  t(10,7,'interior','Floor');
  t(11,7,'interior','Floor');
  t(12,7,'interior','Floor');
  t(13,7,'interior','Wall');
  t(14,7,'interior','');
  t(0,8,'interior','Wall');
  t(1,8,'interior','Floor');
  t(2,8,'interior','Floor');
  t(3,8,'interior','Floor');
  t(4,8,'interior','Floor');
  t(5,8,'interior','Floor');
  t(6,8,'interior','Floor');
  t(7,8,'interior','Floor');
  t(8,8,'interior','Floor');
  t(9,8,'interior','Floor');
  t(10,8,'interior','Floor');
  t(11,8,'interior','Floor');
  t(12,8,'interior','Floor');
  t(13,8,'interior','Wall');
  t(0,9,'interior','Wall');
  t(1,9,'interior','Floor');
  t(2,9,'interior','Floor');
  t(3,9,'interior','Floor');
  t(4,9,'interior','Floor');
  t(5,9,'interior','Floor');
  t(6,9,'interior','Floor');
  t(7,9,'interior','Floor');
  t(8,9,'interior','Floor');
  t(9,9,'interior','Floor');
  t(10,9,'interior','Floor');
  t(11,9,'interior','Floor');
  t(12,9,'interior','Floor');
  t(13,9,'interior','Wall');
  t(0,10,'interior','Wall');
  t(1,10,'interior','Floor');
  t(2,10,'interior','Floor');
  t(3,10,'interior','Floor');
  t(4,10,'interior','Floor');
  t(5,10,'interior','Floor');
  t(6,10,'interior','Floor');
  t(7,10,'interior','Floor');
  t(8,10,'interior','Floor');
  t(9,10,'interior','Floor');
  t(10,10,'interior','Floor');
  t(11,10,'interior','Floor');
  t(12,10,'interior','Floor');
  t(13,10,'interior','Wall');
  t(0,11,'interior','Wall');
  t(1,11,'interior','Wall');
  t(2,11,'interior','Wall');
  t(3,11,'interior','Wall');
  t(4,11,'interior','Wall');
  t(5,11,'interior','Wall');
  t(6,11,'interior','Wall');
  t(7,11,'interior','Wall');
  t(8,11,'interior','Wall');
  t(9,11,'interior','Wall');
  t(10,11,'interior','Wall');
  t(11,11,'interior','Wall');
  t(12,11,'interior','Wall');
  t(13,11,'interior','Wall');

  window.SETTLEMENTS["blank"] = {
    map: m,
    name: "Carrow town",
    isInterior: true,
    entryPos: {x:1, y:1},
  };
})();
